container:
  image: gcc:latest

make_task:
  prep_script: git submodule update --init --recursive
  compile_script: make
  install_script: make install
  checkout_script: checkout https://github.com/hilbix/tinolib.git ../tinolib
  test_script: make test

