Document: suid
Title: Debian suid Manual
Author: <insert document author here>
Abstract: This manual describes what suid is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/suid/suid.sgml.gz

Format: postscript
Files: /usr/share/doc/suid/suid.ps.gz

Format: text
Files: /usr/share/doc/suid/suid.text.gz

Format: HTML
Index: /usr/share/doc/suid/html/index.html
Files: /usr/share/doc/suid/html/*.html
